name: Merge JSON Files

on:
  push:
    paths:
      - "json/**/*.json"
  workflow_dispatch:

jobs:
  merge-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Merge JSON files
        run: node scripts/merge.js

      - name: Minify JSON
        run: |
          npx json-minify dist/owo.json > dist/owo.min.json
          mv dist/owo.min.json dist/owo.json
