name: Merge JSON Files

on:
  push:
    paths:
      - 'json/**/*.json'
  workflow_dispatch:

jobs:
  merge-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # To get the previous commit for the message
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Merge JSON files
        run: node scripts/merge.js

      - name: Minify JSON
        run: |
          npx json-minify dist/owo.json > dist/owo.min.json
          mv dist/owo.min.json dist/owo.json

      - name: Commit dist/owo.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/owo.json
          git commit -m "chore: update dist/owo.json [skip ci]"
          git push

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")
          COMMIT_MSG=$(git log -2 --pretty=%B | head -n 1)  # Get the user's commit message, not the auto-generated one
          gh release create "Commit-$TIMESTAMP" \
            --title "Commit: $TIMESTAMP" \
            --notes "$COMMIT_MSG"
